#!/usr/bin/env node
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync, spawnSync } from 'node:child_process';

const checker = fileURLToPath(new URL('./publish-check.mjs', import.meta.url));
test('scoped decisions reuse only explicit unchanged findings', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'publisher-review-'));
  try {
    const git = (...args) => execFileSync('git', args, { cwd: dir, stdio: 'pipe' });
    git('init');
    git('remote', 'add', 'origin', 'https://github.com/example/review-fixture.git');
    fs.writeFileSync(path.join(dir, 'LICENSE'), 'MIT License\nCopyright (c) 2026 Test Owner\n');
    fs.writeFileSync(path.join(dir, 'SKILL.md'), '---\nname: fixture\ndescription: Use this skill when testing.\n---\n图片必须由生图工具或专业生图 skill 生成。\n');
    git('add', '.');
    git('-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.com', '-c', 'commit.gpgsign=false', 'commit', '-m', 'fixture');
    const scan = (visibility = 'private') => {
      const args = [checker, '--report=report.json', ...(visibility ? [`--visibility=${visibility}`] : [])];
      spawnSync(process.execPath, args, { cwd: dir, stdio: 'pipe' });
      return JSON.parse(fs.readFileSync(path.join(dir, 'report.json'), 'utf8'));
    };
    const first = scan();
    const finding = first.results.find(r => r.detail.startsWith('LICENSE:') && r.reviewId);
    assert.ok(finding);
    assert.equal(first.results.some(r => r.reviewId && r.detail.startsWith('SKILL.md:')), false);
    const receipt = { schemaVersion: 1, scope: first.reviewDecisions.scope, decisions: [{
      reviewId: finding.reviewId, decision: 'keep', userQuote: 'Keep the fixture identity.',
      evidenceRef: 'test-fixture-only', confirmedAt: new Date().toISOString(), revoked: false,
    }] };
    const receiptPath = path.join(dir, '.git', 'publisher-review-decisions.json');
    const save = () => fs.writeFileSync(receiptPath, JSON.stringify(receipt));
    save();
    const reused = r => r.results.some(x => x.reviewId === finding.reviewId && x.decisionReused);
    assert.equal(reused(scan()), true);
    fs.appendFileSync(path.join(dir, 'LICENSE'), '\nUnrelated explanatory sentence.\n');
    assert.equal(reused(scan()), true);
    assert.equal(reused(scan('public')), false);
    assert.equal(reused(scan('')), false);
    receipt.decisions[0].revoked = true; save();
    assert.equal(reused(scan()), false);
    receipt.decisions[0].revoked = false; receipt.decisions[0].userQuote = ''; save();
    assert.equal(reused(scan()), false);
    receipt.decisions[0].userQuote = 'Keep the fixture identity.'; save();
    fs.writeFileSync(path.join(dir, 'LICENSE'), 'MIT License\nCopyright (c) 2026 Changed Owner\n');
    assert.equal(reused(scan()), false);
    fs.appendFileSync(path.join(dir, 'SKILL.md'), '\nGenerated by Example Studio\n');
    assert.ok(scan().results.some(r => r.reviewId && r.detail.startsWith('SKILL.md:')));
    git('remote', 'set-url', 'origin', 'https://github.com/example/other.git');
    assert.notEqual(scan().reviewDecisions.scope, first.reviewDecisions.scope);
    fs.writeFileSync(receiptPath, '{bad');
    assert.ok(scan().results.some(r => r.title === 'Invalid review decision record'));
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});
